//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OriolOr.Maneko.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OriolOr.Maneko.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Month&quot;: &quot;January&quot;,
        ///    &quot;InitialBalance&quot;: 31885.06,
        ///    &quot;FinalBalance&quot;: 30396.86
        ///  },
        ///  {
        ///    &quot;Month&quot;: &quot;February&quot;,
        ///    &quot;InitialBalance&quot;: 32271.70,
        ///    &quot;FinalBalance&quot;: 30447.94
        ///  },
        ///  {
        ///    &quot;Month&quot;: &quot;March&quot;,
        ///    &quot;InitialBalance&quot;: 32334.44,
        ///    &quot;FinalBalance&quot;: 28642.47
        ///  },
        ///  {
        ///    &quot;Month&quot;: &quot;April&quot;,
        ///    &quot;InitialBalance&quot;: 31615.18,
        ///    &quot;FinalBalance&quot;: 29876.61
        ///  }
        ///].
        /// </summary>
        internal static string BankData {
            get {
                return ResourceManager.GetString("BankData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;User&quot;: &quot;oriol.orus.or@gmail.com&quot;,
        ///    &quot;Password&quot;: &quot;04a25483b20c618b77592232e1c59570&quot;,
        ///    &quot;AccountId&quot;: &quot;ES2230250014061400041971&quot;
        ///  }
        ///]
        ///.
        /// </summary>
        internal static string UserData {
            get {
                return ResourceManager.GetString("UserData", resourceCulture);
            }
        }
    }
}
